### ISSUE TITLE
version resource compilation fails due to typo in command line

### ISSUE THREAD

**Issue by michael-kenzel** [microsoft/DirectXShaderCompiler#2320]
The build currently seems to be broken with compilation of `resources\windows_version_resource.rc` failing to locate `version.inc`. The reason for this seems to be a typo in https://github.com/microsoft/DirectXShaderCompiler/blob/aae6b382e8ac2f77b724df13d1989200cc6205ab/cmake/modules/AddLLVM.cmake#L964 causing the include path to be missed. It would seem that `/i` should have been `/I`, which is consistent with the build log:
```
cl : Command line warning D9002 : ignoring unknown option '/i'
```

Changing `/i` to `/I` seems to fix the build.

**Comment by michael-kenzel** [comment]
I submitted a pull request with a fix here: https://github.com/microsoft/DirectXShaderCompiler/pull/2321

**Comment by hekota** [comment]
Fixed by #2321.

**Comment by sunillnaik** [comment]
I have cloned latest master commit fadbe9de8ab2ee8237c5a4079843c856df3cad2a 
and i still see this issue with locating version.inc, I followed the build instructions and tools required.
am I missing anything? I saw the previous fix `/i `to `/I` in 
![version](https://user-images.githubusercontent.com/44568355/61506162-2ea6cb80-aa1c-11e9-90ef-39669fd91ca5.jpg)
cmake\modules\AddLLVM.cmake
Help me with a quick fix.

**Comment by hekota** [comment]
Can you please check if there is a version.inc file in %HLSL_BLD_DIR%\utils\version directory? Please note that this is the build directory, not source directory.

Also is there "Generating version" or "hlsl_version_autogen" anywhere in your build output? Can you please share the build output?

**Comment by sunillnaik** [comment]
Ahh I could fix few issues and now the new versioning is failing, now sure why it enables --official.
maybe issues with my local merge but my build command is just 
hctbuild.cmd -s -vs2017 -spirv

I also tried '-fv' since the -official expects git setup and I have cleaned all git folders to keep clean code.

![Version_issue](https://user-images.githubusercontent.com/44568355/61761303-4bbb1000-ae09-11e9-97cf-1e20d2eb3226.png)

**Comment by hekota** [comment]
Hmm, the -fv flag should work since it does not invoke any git commands. It just copies version.inc from utils\version to <builddir>\utils\version. Did you clean the build directory first with hctclean?

Woraround if that does not help:
In CMakeList.txt in the sources root set HLSL_EMBED_VERSION to OFF (line 82).

Anyway, I created an new issue #2364 to fix this.

**Comment by sunillnaik** [comment]
Ahh strange, it worked with Cmake 3.11.2 not with 3.11.4 my bad, was using wrong version.
I could build now and there are no issues. :-) thank you. It would be helpfull if Cmake version is strictly mentioned in Document and also some about new versioning flags. which internally calls git and may fail if git is not configured.
