### ISSUE TITLE
Using an array in an interpolant does not properly handle values beyond the first entry.

### ISSUE THREAD

**Issue by mkgski** [microsoft/DirectXShaderCompiler#2509]
I'm using the July 2019 release of the source for DXC. Below is a simple VS that reproduces the issue.  FXC emits identical output whether INTERPOLANT_ARRAY_WORKAROUND is defined to 0 or 1.

```
#define INTERPOLANT_ARRAY_WORKAROUND 0

#define NUM_MISC_OUTPUTS 2

struct VSIn
{
float4	Position	: POSITION;
};

struct VSToPS
{
#if INTERPOLANT_ARRAY_WORKAROUND
float4 MiscOutputs0 : MISC0;
float4 MiscOutputs1 : MISC1;
#else
float4 MiscOutputs[NUM_MISC_OUTPUTS] : MISC0;
#endif
float4 Position : SV_Position;
};


void main( VSIn Input, out VSToPS Output )
{
#if INTERPOLANT_ARRAY_WORKAROUND
Output.MiscOutputs0 = Input.Position;
Output.MiscOutputs1 = Input.Position;
#else
[unroll]
for(uint i = 0; i < NUM_MISC_OUTPUTS; ++i)
{
Output.MiscOutputs[i] = Input.Position;
}
#endif
Output.Position = Input.Position;
}
```

And some disassembly exceprts for comparison:
INTERPOLANT_ARRAY_WORKAROUND = 0
```
; Output signature:
;
; Name                 Index             InterpMode DynIdx
; -------------------- ----- ---------------------- ------
; MISC                     0                 linear       
; SV_Position              0          noperspective       
```
```
!0 = !{!"clang version 3.7.0 (tags/RELEASE_370/final)"}
!1 = !{i32 1, i32 0}
!2 = !{i32 1, i32 5}
!3 = !{!"vs", i32 6, i32 0}
!4 = !{[6 x i32] [i32 4, i32 12, i32 273, i32 546, i32 1092, i32 2184]}
!5 = !{void ()* @main, !"main", !6, null, null}
!6 = !{!7, !11, null}
!7 = !{!8}
!8 = !{i32 0, !"POSITION", i8 9, i8 0, !9, i8 0, i32 1, i8 4, i32 0, i8 0, !10}
!9 = !{i32 0}
!10 = !{i32 3, i32 15}
!11 = !{!12, !14}
!12 = !{i32 0, !"MISC", i8 9, i8 0, !13, i8 2, i32 2, i8 4, i32 0, i8 0, !10}
!13 = !{i32 0, i32 1}
!14 = !{i32 1, !"SV_Position", i8 9, i8 3, !9, i8 4, i32 1, i8 4, i32 2, i8 0, !10}
```

INTERPOLANT_ARRAY_WORKAROUND  = 1
```
; Output signature:
;
; Name                 Index             InterpMode DynIdx
; -------------------- ----- ---------------------- ------
; MISC                     0                 linear       
; MISC                     1                 linear       
; SV_Position              0          noperspective       
```
```
!0 = !{!"clang version 3.7.0 (tags/RELEASE_370/final)"}
!1 = !{i32 1, i32 0}
!2 = !{i32 1, i32 5}
!3 = !{!"vs", i32 6, i32 0}
!4 = !{[6 x i32] [i32 4, i32 12, i32 273, i32 546, i32 1092, i32 2184]}
!5 = !{void ()* @main, !"main", !6, null, null}
!6 = !{!7, !11, null}
!7 = !{!8}
!8 = !{i32 0, !"POSITION", i8 9, i8 0, !9, i8 0, i32 1, i8 4, i32 0, i8 0, !10}
!9 = !{i32 0}
!10 = !{i32 3, i32 15}
!11 = !{!12, !13, !15}
!12 = !{i32 0, !"MISC", i8 9, i8 0, !9, i8 2, i32 1, i8 4, i32 0, i8 0, !10}
!13 = !{i32 1, !"MISC", i8 9, i8 0, !14, i8 2, i32 1, i8 4, i32 1, i8 0, !10}
!14 = !{i32 1}
!15 = !{i32 2, !"SV_Position", i8 9, i8 3, !9, i8 4, i32 1, i8 4, i32 2, i8 0, !10}
```

**Comment by tex3d** [comment]
There was an Nvidia driver bug impacting array elements that was fixed a while back.  Update your driver and see if it's fixed.

The portion of output signature text you pasted here is just for listing the interpolation mode for each DxilSignatureElement.  When you have an array element, it's one element in this table, but will be multiple rows in the table that shows packing.  That's just a disassembly quirk.

**Comment by mkgski** [comment]
Thanks for the info, much appreciated.  I just double checked on 436.30 (~mid September so pretty recent) and the issue is still present.  Sounds like I'll have to contact our NVidia rep.

**Comment by pow2clk** [comment]
Closing under the assumption this is an NVIDIA driver issue.
