### ISSUE TITLE
Incorrect SPIR-V generated when `firstbithigh` is used on a `uint64_t`

### ISSUE THREAD

**Issue by manon-traverse** [microsoft/DirectXShaderCompiler#4702]
```
generated SPIR-V is invalid: GLSL.std.450 FindUMsb: expected all operands to have the same bit width as Result Type
  %137 = OpExtInst %uint %1 FindUMsb %136

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Calling this function causes the error when targeting SPIR-V. It works fine when targeting DXIL.
```HLSL
uint clz64(uint64_t v) { return 63 - firstbithigh(v); }
```

It does work with the following workaround:
```HLSL
uint clz64(uint64_t v) {
    uint2 workaround = uint2(v, v >> 32);

    uint high = firstbithigh(workaround.y);
    if (high != -1) {
        return 31 - high;
    } else {
        return 63 - firstbithigh(workaround.x);
    }
}
```

**Comment by godlikepanos** [comment]
`FindUMsb` and a few similar GLSL derived instructions do not support 64bit (see https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html). glslang has (or had) similar issues. I think Khronos should extend the instructions to support 64bit and in the meantime DXC should apply your workaround.

**Comment by sudonatalie** [comment]
DXC now emits an appropriate error message when `firstbithigh` is used on a `uint64_t`. Eventually we should support this, but it's not currently a priority to implement so the workaround in HLSL should be used until then.

```
int firstbithigh64(uint64_t v) {
    int high = firstbithigh(uint(v >> 32));
    if (high != -1) {
      return high + 32;
    }

    return firstbithigh(uint(v));
}
```

**Comment by LukasBanana** [comment]
The fix b7a50ba introduced a new issue at [astContext.getTypeSize(argType) == 64](https://github.com/microsoft/DirectXShaderCompiler/commit/b7a50ba6d7baadfc55773363c32ae0978902f14f#diff-6b86e3fcb3f49e0a10dd39cc10c7ec49d6c00bf11422c86743ef63a34eac6303R8814) when used on `int2` types. This reproduces the issue (see [godbolt.org](https://godbolt.org/z/hrj5rz1xj)):
```hlsl
// -T vs_6_0 -E VSMain -spirv
int2 Foo;
void VSMain() {
    firstbithigh(Foo);
}
```

**Comment by sudonatalie** [comment]
Thanks for catching that @LukasBanana! Submitting a fix now.

**Comment by damyanp** [comment]
@s-perron - comments here seem to suggest this is already fixed?

**Comment by sudonatalie** [comment]
Just to clarify, the original issue in the bug is not yet fixed. I added some error messaging to make the failure more explicit, and in the process was accidentally overzealous and errored on some valid cases, so I fixed that, but the SPIR-V backend still doesn't support `firstbithigh` on 64 bit ints.

**Comment by s-perron** [comment]
We will not be implementing the workaround in the compiler. We will reconsider in the clang implementation.

#6864 is open to make sure the error messages are reasonable.
