### ISSUE TITLE
ShaderOpTest.{cpp,h} does not support hardware devices

### ISSUE THREAD

**Issue by jholewinski** [Microsoft/DirectXShaderCompiler#74]
The DXIL tests in `clang-hlsl-tests.dll` do not all support running on hardware (without source modifications).

ShaderOpTest.h:

```c++
 bool UseWarpDevice = true;
```

ShaderOpTest.cpp:

```c++
    if (m_pShaderOp->UseWarpDevice) {                                                                         
      CComPtr<IDXGIAdapter> warpAdapter;                                                                      
      CHECK_HR(factory->EnumWarpAdapter(IID_PPV_ARGS(&warpAdapter)));                                         
      CHECK_HR(D3D12CreateDevice(warpAdapter, FeatureLevelRequired,                                           
                                 IID_PPV_ARGS(&pDevice)));                                                    
    } else {                                                                                                  
      CComPtr<IDXGIAdapter1> hardwareAdapter;                                                                 
      GetHardwareAdapter(factory, m_pShaderOp->AdapterName, &hardwareAdapter);                                
      if (hardwareAdapter == nullptr) {                                                                       
        CHECK_HR(HRESULT_FROM_WIN32(ERROR_NOT_FOUND));                                                        
      }                                                                                                       
      CHECK_HR(D3D12CreateDevice(hardwareAdapter, FeatureLevelRequired,                                       
                                 IID_PPV_ARGS(&pDevice)));                                                    
    }    
```

There are no other accesses (in particular, writes) to `UseWarpDevice`, meaning all runs will use WARP, regardless of hardware support.

**Comment by marcelolr** [comment]
Thanks for filing the issue.

We're looking at allowing the device to be provided for the test (a sort of middle-ground between "do everything from the test description" and "we've got a window ready for display, please hook into that"). Stay tuned.

**Comment by tex3d** [comment]
Closing, as I believe this is fixed.  Open another issue if there are more problems.

**Comment by jholewinski** [comment]
I'm still unable to run the following tests on a hardware device due to this issue:

BasicTriangleOpTest
MinMaxTest
OutOfBoundsTest
SaturateTest
DoShaderOpArithTest
